services:
  vlfm-app:
    image: dcon_habitat_vlfm:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      # HOST_PATH : CONTAINER_PATH
      - .:/workspace/vlfm               # Maps your code
      - ./data:/workspace/vlfm/data     # Maps your big downloads
      - ./cache:/root/.cache            # Maps your AI models/weights
    stdin_open: true
    tty: true
    working_dir: /workspace/vlfm