# @package habitat.dataset
defaults:
  - /habitat/dataset: dataset_config_schema
  - _self_
type: ObjectNav-v1
split: val
scenes_dir: data/scene_datasets
content_scenes:
- '*'
data_path: data/datasets/objectnav/gibson/v1.1/{split}/{split}.json.gz